name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  misleading:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - id: check-misleading
        uses: ./
        with:
          name: paoc
          list: poac poacpp
          distance: 2

      - name: Test the result
        run: |
          [ '${{ steps.check-misleading.outputs.is-misleading }}' = 'true' ]

  not-misleading:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - id: check-not-misleading
        uses: ./
        with:
          name: paoc
          list: poac poacpp

      - name: Test the result
        run: |
          [ '${{ steps.check-not-misleading.outputs.is-misleading }}' = 'false' ]
